- name: slave
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    -  name: update 
       apt:
        update_cache: yes

    - name: download the script
      shell: 'curl -fsSL https://get.docker.com -o get-docker.sh'

    - name: run the script
      shell: bash /home/ubuntu/get-docker.sh

    - name: adding existing user to group sudo
      user:
          name: 'ubuntu'
          groups: docker
          append: yes

    - name: check that docker is intalled
      service:
        name: docker
        state: started
        enabled: yes 

    - name: Run docker container
      shell: 'docker run  -d -it -p 80:80 nginx   bash' 
